version: '3.8'

services:
  # -----------------------------
  # 1. MLflow Tracking Server
  # -----------------------------
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0
    volumes:
      - ./mlflow_data:/mlflow
    networks:
      - mlops_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  trainer:
    build:
      context: .
      dockerfile: docker/trainer/Dockerfile
    container_name: mlflow_trainer
    depends_on:
      - mlflow
    environment:
      # It needs to know where MLflow is inside the docker network
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      # It needs to save artifacts to the shared volume
      - ./mlflow_data:/mlflow
    networks:
      - mlops_net
    # Important: We don't want this to restart forever after it finishes training
    restart: "no" 

  api:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: diabetes_api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
      # We usually don't depend on trainer because trainer finishes and dies.
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlflow_data:/mlflow
    networks:
      - mlops_net

networks:
  mlops_net:
    driver: bridge